spring.application.name=Fluxia
server.port=8085

# Connexion à MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/fluxia_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Pass@123

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false